default: &default
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci

development:
  <<: *default
  host: localhost
  database: <%= ENV.fetch("DATABASE_NAME") %>
  username: <%= ENV.fetch("DATABASE_USER") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
