default: &default
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci

development:
  <<: *default
  host: localhost
  database: <%= ENV.fetch("DATABASE_NAME") %>
  username: <%= ENV.fetch("DATABASE_USER") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>


test:
  <<: *default
  host: 127.0.0.1
  database: <%= ENV.fetch("DATABASE_NAME_TEST") %>
  username: <%= ENV.fetch("DATABASE_USER") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>

production:
  <<: *default
  host: <%= ENV.fetch("DATABASE_HOST") %>
  database: <%= ENV.fetch("DATABASE_NAME_PROD") %>
  username: <%= ENV.fetch("DATABASE_USER") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
